### ISSUE TITLE
dns-mod doesn't read HOSTALIASES yet

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#1013] opened 2020-08-10 19:27 UTC
if loadmodule dns is commented out, eggdrop core will use libc functions getaddrinfo(3), gethostbyname(3) which will use HOSTALIASES, see hostname(7).

but if eggdrop dns module is used, those functions wont be used.

HOSTALIASES are like /etc/hosts, not part of dns protocol / server and are currently, like /etc/hosts, not implemented in eggdrop dns module.

If you dont stop me, i would like to implement HOSTALIASES for eggdrop dns mod, like i did did for /etc/hosts with pending #701, but in a new PR.

Im looking forward for rewiewing / merging of #701, so it wont overlap with this new PR.

**Comment by vanosg** [comment] 2020-08-10 21:16
Duplicate of 1011... lets keep everything in one thread.

**Closed as completed by vanosg** 2020-08-10 21:16 UTC
