### ISSUE TITLE
Segmentation fault when issuing restart command in PL

### ISSUE THREAD

**Issue by tydel** [eggheads/eggdrop#1715] opened 2024-11-12 01:27 UTC
Last night, I tried to restart one of my bots by issuing a .restart in the partyline and the bot had a segmentation fault.

```
[12:16:43] #tydel# restart
Restarting.
[12:16:42] Restarting ...
[12:16:42] Module unloaded: ident
[12:16:42] Module unloaded: ctcp
[12:16:42] Module unloaded: console
[12:16:42] Module unloaded: compress
[12:16:42] Sending 'share end' to all sharebots...
[12:16:42] Unloaded sharing module, flushing tbuf's...
[12:16:42] Module unloaded: share
[12:16:42] Unloading transfer module, killing all transfer connections...
[12:16:42] Module unloaded: transfer
[12:16:42] Stagnant modules; there WILL be memory leaks!
[12:16:42] * Please report problem to https://github.com/eggheads/eggdrop/issues
[12:16:42] * Check doc/BUG-REPORT on how to do so.
[12:16:42] * Last bind (may not be related): cl_mode
[12:16:42] * Wrote DEBUG
[12:16:42] * SEGMENT VIOLATION -- CRASHING!
```

DEBUG contents:

**`removed`**

**Comment by vanosg** [comment] 2024-11-12 01:43
This is a duplicate of #1701 . Thanks for reporting, we'll track it there.

**Closed as completed by vanosg** 2024-11-12 01:43 UTC
