### ISSUE TITLE
bot won't join channel 

### ISSUE THREAD

**Issue by netcrave** [eggheads/eggdrop#509] opened 2018-02-17 15:44 UTC
.-chan #netcrave
#netcrave is no longer a valid channel, changing your console to '*'
Channel #netcrave removed from the bot.
This includes any channel specific bans, invites, exemptions and user records that you set.
[07:42:11] #catgirl# -chan #netcrave
.+chan #netcrave
[07:42:42] #catgirl# +chan #netcrave

but bot is connected: 

07:44 [EFNet2] ::: lemondrop [lemondrop@shells.yourstruly.sx]
07:44 [EFNet2] :::  ircname  : /msg lemondrop hello
07:44 [EFNet2] :::  server   : irc.colosolutions.net [Colosolutions, Inc. - Orlando, FL]
07:44 [EFNet2] :::  hostname : 206.125.168.69
07:44 [EFNet2] ::: End of WHOIS

**Comment by netcrave** [comment] 2018-02-17 15:46
branch develop, commit: 

```
commit 10ad04040eeff0c9fc422c6fd9b85f02329717ad
Author: Geo <geo@eggheads.org>
Date:   Sun Feb 4 15:39:56 2018 +0000

    Update THANKS file
```

**Comment by vanosg** [comment] 2018-02-17 16:49
Hi netcrave, thanks for reporting. Can you elaborate a little more on what the problem is, and a little more on the background of how it occurred? I think you're saying that it doesn't join a channel after adding it to the bot. Does it happen all the time? Does it only happen after removing it? 

Can you please provide the output of .status to show what the eggdrop thinks it is supposed to be doing? Along with any other info you can

I cannot reproduce the issue here locally (and this is pretty well-traversed code)... you may want to check other external factors, like is there a key or invite mode set on the channel

Thanks

**Comment by netcrave** [comment] 2018-02-18 01:30
telnet shells.yourstruly.sx 5555

user: catgirl
password: aaSX9MzcgHzhqMAA

And if you can give me a pubkey i'll give you access to the user.

**Comment by netcrave** [comment] 2018-02-18 01:44
sorry two people on this account at once, yes thats fine I dont mind you having access to the bot its for testing at the moment, the goal is to figure out whats going on so if you can give me a pubkey I can give you shell access to the bot or you can telnet and see yourself or both, either way the goal is to join the bot to #netcrave on efnet

**Comment by thommey** [comment] 2018-02-18 01:46
this is a public website. billions of people can read it and someone will surely abuse that access and ruin your bot, channels, possibly more. please change that password ASAP. you just can't post that here. I will let @vanosg get back to you, but it would help if you could answer his questions yourself.

**Comment by vanosg** [comment] 2018-02-20 02:24
Pending additional information requested, I'm closing this as it seems to be a usage question, not anything to do with code. Please join #eggdrop on freenode and someone may be able to help you further.

**Closed by vanosg** 2018-02-20 02:24 UTC
