### ISSUE TITLE
Feature Request: Tertiary (or Ternary) Botnet Linking

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#579] opened 2018-08-25 22:12 UTC
Copied from #550:

Which reminds me: +t (for ternary/tertiary link): that idea died? :( With a large botnet, either a 3rd-link or an ordered link would be useful (botattrs of +0 (primary choice) .. +9 (last choice), in order) would be nice. However, waiting for 10 attempts to connect would mean 10 minutes before coming around to the hub again. This is where obeying $::connect-timeout would be useful (and make the process quicker).

**Comment by Cizzle** [comment] 2018-08-25 22:49
Duplicate of #357

**Comment by maimizuno** [comment] 2018-08-26 00:56
Wow, what a jerk! ( I know you can see this on channel, which is fine; he's making this public.)

"Botnet links: 3rd level option" seems kinda obvious, doesn't it? But let's dig even deeper, since you feel it's appropriate to put this on a public forum .... This is very unprofessional of you. IF you'd bother to =====READ===== the damned original, you'd know that you're WAY OFF BASE!!

Here. Let me help you! ![cizzle](https://user-images.githubusercontent.com/8587591/44623853-64384880-a88f-11e8-9620-0554d730d40a.png)

I put a new report here because the other issue WAS CLOSED WITHOUT COMMENT ON THIS PARAGRAPH!!!!!!!!!!!!!!!!!!!!!! Now who looks stupid? Do your homework before you spout your mouth off!

I demand you delete that comment, and, come to my network and apologize to me.

**Closed as completed** 2019-10-15 04:03 UTC
