### ISSUE TITLE
DCC file send / chat issues (IP variables)

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#413] opened 2017-06-01 07:47 UTC
Even respecting all of the config-file notes about setting nat-up / listen-addr / vhost4 & vhost6 / prefer-upv6. and my-ip, there's one scenario that isn't mentioned:

When a bot is behind a router (NAT) on a single IP (think: home network on a router), while DCC CHAT can be mitigated (somewhat) with the proper combination of variables, DCCSEND (file sending) does not obey this fully!

DCCSEND will obey $::net-ip only.

[s->] PRIVMSG Domino :DCC SEND leather_wear.txt 128129XXXX 23710 2351

This LONGIP resolves to my WAN IP address (set in $::nat-ip). The only way to get the bot to send directly to me, successfully, is:

(1) set $::nat-ip to the bot's LAN address
-- DCC CHAT works only for me; fails for others not on my LAN
-- DCCME (scripted command) I have to punch holes in my firewall to allow it to work.
-- DCCSEND works only or me; fails for all others

(2) with $::nat-ip set to WAN address
-- DCC CHAT works for others not on my LAN (if I have holes punched through my firewall). Fails for me
-- DCCME works only if I have holes punched through my firewall, AND,  configure reserved-portrange , AND, my chat client (mIRC) is set up to use specific (matching) port ranges
-- DCCSEND fails for me, works for all others

No combination works for all circumstances.

**Comment by vanosg** [comment] 2017-07-08 06:04
Are you and the bot on the same LAN in this scenario?

**Comment by ghost** [comment] 2017-07-09 00:34
We are on the same LAN, yes. Though, to be thorough, I moved the bot to another location [box]; and there we no changes to the results.

**Comment by vanosg** [comment] 2017-07-09 00:54
Another location on the same LAN?

**Comment by ghost** [comment] 2017-07-09 02:23
not same LAN; completely diff* box/IP.

**Comment by vanosg** [comment] 2017-07-09 02:36
I'm a little more confused over what the problem is now, then - there are some networking configuration tricks that need to happen if you're both on the same LAN, but if it outside your LAN, nat-ip should be set to the bot's WAN ip, port forwarding should configured to allow to the reserved portrange. 

So, for clarity, this is how I see it should be working, on a bot not on your LAN, with nat-ip set to WAN, and the bot's router properly set to port forward the reserved portrange:
- You should be able to ctcp chat the bot (Bot sends its nat-ip IP). 
- You should be able to dcc chat the bot, if you have set a port range for DCC in your client and set up your LAN router to port forward (you can test this by DCC chat'ing someone else who is not the bot, just to confirm it works in general and is not the bot's fault) (This is independent of any bot setting)
- The Tcl command 'dccsend', when used on the bot, should initiate a send request to you, using the IP you set in nat-ip. 
- I don't know what DCCME is/does

And again, this will not be true if the bot resides on the same LAN as you, this is only for a bot behind a NAT on a different network. Is everything I listed above true for you on this scenario? Thanks

**Comment by ghost** [comment] 2017-07-09 02:47
Clarification: "DCCME" just makes the bot send a "dcc chat" request to the client, to initiate the DCC CHAT from the other side (ctcp dcc).

**Comment by ghost** [comment] 2017-07-09 02:48
I will play with the configurations more; if I can provide more insight, I'll comment further.

**Comment by vanosg** [comment] 2018-01-19 03:46
Is there any further comment on this issue, or can I close it?

**Comment by ghost** [comment] 2018-02-05 18:37
I am unable to provide any further tesdting (due to personal circumstances). Close; I will re-comment if the issue is found again.

**Closed as completed** 2018-07-30 16:45 UTC
